# Generated by Django 3.0 on 2021-03-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
